# Generated by Django 4.1 on 2023-04-25 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 16, 27, 9, 705062)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 16, 27, 9, 705062)),
        ),
    ]
