# Generated by Django 4.1 on 2023-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(max_length=500)),
                ('media_type', models.CharField(max_length=20)),
                ('target', models.IntegerField()),
                ('currrent_amount', models.ImageField(upload_to='')),
                ('heart', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('donation_tpe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(max_length=500)),
                ('profile_image_url', models.CharField(max_length=500)),
                ('profile_username', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('running_status', models.CharField(max_length=100)),
            ],
        ),
    ]
