# Generated by Django 4.1 on 2023-04-26 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_login_details_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 8, 35, 26, 73053)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 8, 35, 26, 72023)),
        ),
    ]
