# Generated by Django 4.1 on 2023-04-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_donations_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='donation_tpe',
            new_name='donation_type',
        ),
    ]
