# Generated by Django 4.1 on 2023-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_donation_tpe_donations_donation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='currrent_amount',
        ),
        migrations.AddField(
            model_name='donations',
            name='current_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donation_type',
            field=models.CharField(default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='donations',
            name='heart',
            field=models.IntegerField(default=0),
        ),
    ]
