# Generated by Django 4.1 on 2023-04-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_categories_image_url_alter_login_details_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=''),
        ),
    ]
