# Generated by Django 4.1 on 2023-05-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('public_email_id', models.CharField(max_length=100)),
                ('user_email_id', models.CharField(max_length=100)),
                ('user_contact', models.IntegerField(default=None)),
                ('donation_title', models.CharField(max_length=300)),
                ('donation_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='storage',
            name='media',
            field=models.FileField(upload_to='media'),
        ),
    ]
