# Generated by Django 4.1 on 2023-04-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_login_details_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='image_url',
        ),
    ]
