# Generated by Django 4.1 on 2023-04-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_donations_currrent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='running_status',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
