# Generated by Django 4.1 on 2023-05-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_donation_payment_alter_storage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_payment',
            name='user_contact',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
