# Generated by Django 4.1 on 2023-04-13 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_featured_running_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 16, 45, 50, 491492)),
        ),
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
