# Generated by Django 4.1 on 2023-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_donation_payment_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
