# Generated by Django 4.1 on 2023-04-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_categories_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
