# Generated by Django 4.1 on 2023-05-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_user_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_wallet',
            old_name='email_id',
            new_name='email',
        ),
    ]
