# Generated by Django 4.1 on 2023-04-13 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_users_login_type_users_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 19, 6, 32, 259988)),
        ),
    ]
