# Generated by Django 4.1 on 2023-04-13 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_users_dob_alter_users_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 19, 6, 39, 639126)),
        ),
    ]
