# Generated by Django 4.1 on 2023-04-20 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_users_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image_1_url', models.CharField(max_length=300)),
                ('image_2_url', models.CharField(max_length=300)),
                ('image_3_url', models.CharField(max_length=300)),
                ('image_4_url', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='donations_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='donations_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 20, 11, 29, 52, 808202)),
        ),
    ]
