# Generated by Django 4.1 on 2023-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_donations_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('user_email_id', models.CharField(max_length=200)),
            ],
        ),
    ]
