# Generated by Django 4.1 on 2023-05-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_bank_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='funding_account',
            field=models.CharField(choices=[('amarshan', 'amarshan'), ('user', 'user')], default='', max_length=200),
        ),
    ]
