# Generated by Django 4.1 on 2023-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_donations_funding_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithDraw_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('user_email_id', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('not_approved', 'not_approved')], default='pending', max_length=100)),
            ],
        ),
    ]
