# Generated by Django 4.1 on 2023-04-20 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_products_category_alter_products_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 20, 21, 54, 34, 601975)),
        ),
    ]
