# Generated by Django 4.1 on 2023-06-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_donations_funding_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_requests',
            name='donation_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
