# Generated by Django 4.1 on 2023-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_users_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='donations',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
