# Generated by Django 4.1 on 2023-04-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_donation_categories_donations_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('not_approved', 'not_approved')], default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='building_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='street_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
