# Generated by Django 4.1 on 2023-04-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_notification_donations_status_users_building_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField()),
            ],
        ),
    ]
