# Generated by Django 4.1 on 2023-04-23 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 11, 41, 17, 1245)),
        ),
    ]
