# Generated by Django 4.1 on 2023-04-23 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_alter_login_details_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='device',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='donations',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='donations',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 18, 7, 18, 450689)),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 18, 7, 18, 449696)),
        ),
    ]
