# Generated by Django 4.1 on 2023-04-23 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_login_details_device_alter_donations_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 18, 57, 5, 884194)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 18, 57, 5, 884194)),
        ),
    ]
