# Generated by Django 4.1 on 2023-04-25 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_orders_donation_categories_image_url_users_landmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 13, 11, 52, 132590)),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 13, 11, 52, 132590)),
        ),
    ]
