# Generated by Django 4.1 on 2023-04-25 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_remove_orders_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 15, 35, 27, 453253)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('cancelled', 'cancelled'), ('shipping', 'shipping'), ('ordered', 'ordered'), ('processing', 'processing')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='joining_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 15, 35, 27, 451856)),
        ),
    ]
